FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --configuration=production

FROM nginx:stable-alpine
COPY --from=build /app/dist/TeamsCord/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
